kind: Service
apiVersion: v1
metadata:
  name: mc-account-service
  namespace: development
  labels:
    prometheus: magecoffee
spec:
  selector:
    app: mc-account-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080